{{if .Values.ui.ingress.enabled -}}
{{$fullName := include "domaudit.fullname" . -}}
{{- $svcPort := .Values.ui.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "domaudit.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ui.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- range $_, $path := .Values.ui.ingress.paths }}
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      rewrite "(?i)/{{ $path }}/(.*)" /$1 break;
      rewrite "(?i)/{{ $path }}$" / break;
  {{- end}}
    {{- include "common.ingress.uiistioAnnotations" . | nindent 4 }}
spec:
  {{- include "common.ingress.uifullspec" . | indent 2 }}
{{- end }}
